#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Reo Isaka
# SPDX-License-Identifier: BSD-3-Clause


import sys

def convert(text):
    hiragana = ["あ", "い", "う", "え", "お"]    #ひらがなのリスト
    romaji = ["a", "i", "u", "e", "o"]    #ひらがなに対するローマ字のリスト

    output = ""    #outputという変数を作り，""で文字列を空にしている
    i = 0    #処理している文字の位置を示している

    while i < len(text):    #文字列の長さを超えるまで処理を続ける
        for k in range(len(hiragana)):    #ひらがなのリストの長さを数値にしてkに代入する
            if text.startswith(hiragana[k], i):    #現在の位置から，ひらがなが一致するかを調べる
                output += romaji[k]    #一致したひらがなに対応するローマ字を追加する
                i += len(hiragana[k])    #ひらがなを１文字進める
                break

        else:
            output += text[i]    #ひらがなのリストになかった場合，その文字をoutputに追加する
            i += 1    #次の文字の処理を始める

    return output


for text in sys.stdin:    #標準入力を読み取り，textに格納する
    if text.strip():    #textに入力があったら関数を呼び出し，その結果をoutextに格納する
        txt = convert(text)
        print(txt)
        break
